### ISSUE TITLE
ag-grep

### ISSUE THREAD

**Issue by daviderestivo** [sriramkswamy/dotemacs#1]
Hi Sriram,

first of all I would like to thank you for having taken the time to write down such an interesting dotemacs. I'm using many of your settings into my init.el making my "editing" life much simpler.
At the moment I'm struggling in making the below section working on macOS. I have installed "The Silver Searcher" via homebrew and the only executable I have is 'ag'. So, I have modified the below config section of your init file:

```
(when (executable-find "ag-grep")
    (setq helm-grep-default-command "ag-grep -Hn --no-group --no-color %e %p %f"
          helm-grep-default-recurse-command "ag-grep -H --no-group --no-color %e %p %f"))
```
with

```
(when (executable-find "ag")
    (setq helm-grep-default-command "ag -Hn --no-group --no-color %e %p %f"
          helm-grep-default-recurse-command "ag -H --no-group --no-color %e %p %f"))
```

but it does not seems to work properly. Thanks in advance for your help.

Regards,
Davide

**Comment by sriramkswamy** [comment]
Thanks for the compliments. I'm glad it is useful.

That code was written long ago and what you did seems like it should work. Could you give more information on what is the error and what isn't working?

Also, I think helm adapted ag into a command by default now with [a command](https://github.com/emacs-helm/helm/wiki/Grep). So, maybe this will help you.

**Comment by daviderestivo** [comment]
Ciao Sriram,

it does not do any search but simply show as a result "Ag". I've gone through the document you linked. I assume you refer to: 

```
(setq helm-grep-ag-command "ag --line-numbers -S --hidden --color --color-match '31;43' --nogroup %s %s %s")
(setq helm-grep-ag-pipe-cmd-switches '("--color-match '31;43'"))
```
This is set by default but I would expect to see an 'ag' process spawn during the search but I don't see it.

Regards,
Davide

**Comment by sriramkswamy** [comment]
I apologize on getting to this late. I had a busy couple of weeks.

I'm not sure I'll be able to reproduce your bug with respect to setting the `helm-grep-default-command` since it's been quite a while since I tested helm out. However, I remember that ag worked fine when I used `helm-do-grep-ag` (or something like that). Is this a command that you see in your helm configuration?

**Comment by daviderestivo** [comment]
Hi Sriram,

I guess I found out the problem. The "--vimgrep" ag option needs to be enabled for helm to be able to parse the ag output properly. Below a working config example:

```
  ;; Replace the default helm grep command with ag.
  ;; Requires "The Silver Searcher" (ag) to be installed.
  ;; On macOS use: 'brew install the_silver_searcher'
  (when (executable-find "ag")
    ;; For helm to recognize correctly the matches we need to enable
    ;; line numbers and columns in its output, something the
    ;; --vimgrep option does.
   (setq helm-grep-default-command         "ag --vimgrep --nogroup --nocolor -z %p %f"
         helm-grep-default-recurse-command "ag --vimgrep --nogroup --nocolor -z %p %f"))
```

I guess we can close this issue. 

Thanks and regards,
Davide

**Comment by sriramkswamy** [comment]
Thank you for letting me know. I'll change this in my config as well.
